export const US_STATES: { abbr: string; name: string }[] = [
  { abbr: 'AL', name: 'Alabama' },
  { abbr: 'AK', name: 'Alaska' },
  { abbr: 'AZ', name: 'Arizona' },
  { abbr: 'AR', name: 'Arkansas' },
  { abbr: 'CA', name: 'California' },
  { abbr: 'CO', name: 'Colorado' },
  { abbr: 'CT', name: 'Connecticut' },
  { abbr: 'DE', name: 'Delaware' },
  { abbr: 'FL', name: 'Florida' },
  { abbr: 'GA', name: 'Georgia' },
  { abbr: 'HI', name: 'Hawaii' },
  { abbr: 'ID', name: 'Idaho' },
  { abbr: 'IL', name: 'Illinois' },
  { abbr: 'IN', name: 'Indiana' },
  { abbr: 'IA', name: 'Iowa' },
  { abbr: 'KS', name: 'Kansas' },
  { abbr: 'KY', name: 'Kentucky' },
  { abbr: 'LA', name: 'Louisiana' },
  { abbr: 'ME', name: 'Maine' },
  { abbr: 'MD', name: 'Maryland' },
  { abbr: 'MA', name: 'Massachusetts' },
  { abbr: 'MI', name: 'Michigan' },
  { abbr: 'MN', name: 'Minnesota' },
  { abbr: 'MS', name: 'Mississippi' },
  { abbr: 'MO', name: 'Missouri' },
  { abbr: 'MT', name: 'Montana' },
  { abbr: 'NE', name: 'Nebraska' },
  { abbr: 'NV', name: 'Nevada' },
  { abbr: 'NH', name: 'New Hampshire' },
  { abbr: 'NJ', name: 'New Jersey' },
  { abbr: 'NM', name: 'New Mexico' },
  { abbr: 'NY', name: 'New York' },
  { abbr: 'NC', name: 'North Carolina' },
  { abbr: 'ND', name: 'North Dakota' },
  { abbr: 'OH', name: 'Ohio' },
  { abbr: 'OK', name: 'Oklahoma' },
  { abbr: 'OR', name: 'Oregon' },
  { abbr: 'PA', name: 'Pennsylvania' },
  { abbr: 'RI', name: 'Rhode Island' },
  { abbr: 'SC', name: 'South Carolina' },
  { abbr: 'SD', name: 'South Dakota' },
  { abbr: 'TN', name: 'Tennessee' },
  { abbr: 'TX', name: 'Texas' },
  { abbr: 'UT', name: 'Utah' },
  { abbr: 'VT', name: 'Vermont' },
  { abbr: 'VA', name: 'Virginia' },
  { abbr: 'WA', name: 'Washington' },
  { abbr: 'WV', name: 'West Virginia' },
  { abbr: 'WI', name: 'Wisconsin' },
  { abbr: 'WY', name: 'Wyoming' },
]

export const METROS_BY_STATE: Record<string, string[]> = {
  AL: ['Birmingham', 'Huntsville', 'Mobile', 'Montgomery', 'Tuscaloosa'],
  AK: ['Anchorage', 'Fairbanks', 'Juneau'],
  AZ: ['Flagstaff', 'Mesa', 'Phoenix', 'Scottsdale', 'Tempe', 'Tucson'],
  AR: ['Fayetteville', 'Fort Smith', 'Little Rock'],
  CA: ['Bakersfield', 'Fresno', 'Long Beach', 'Los Angeles', 'Oakland', 'Riverside', 'Sacramento', 'San Diego', 'San Francisco', 'San Jose', 'Santa Barbara', 'Santa Cruz', 'Stockton'],
  CO: ['Boulder', 'Colorado Springs', 'Denver', 'Fort Collins', 'Grand Junction', 'Pueblo'],
  CT: ['Bridgeport', 'Hartford', 'New Haven', 'Stamford', 'Waterbury'],
  DE: ['Dover', 'Wilmington'],
  FL: ['Fort Lauderdale', 'Fort Myers', 'Gainesville', 'Jacksonville', 'Miami', 'Orlando', 'Sarasota', 'St. Petersburg', 'Tallahassee', 'Tampa'],
  GA: ['Athens', 'Atlanta', 'Augusta', 'Columbus', 'Macon', 'Savannah'],
  HI: ['Honolulu', 'Kailua', 'Maui'],
  ID: ['Boise', 'Idaho Falls', 'Nampa', 'Pocatello', 'Twin Falls'],
  IL: ['Aurora', 'Chicago', 'Peoria', 'Rockford', 'Springfield'],
  IN: ['Bloomington', 'Evansville', 'Fort Wayne', 'Indianapolis', 'South Bend'],
  IA: ['Cedar Rapids', 'Davenport', 'Des Moines', 'Iowa City', 'Sioux City'],
  KS: ['Kansas City', 'Overland Park', 'Topeka', 'Wichita'],
  KY: ['Bowling Green', 'Lexington', 'Louisville'],
  LA: ['Baton Rouge', 'Lafayette', 'New Orleans', 'Shreveport'],
  ME: ['Bangor', 'Portland'],
  MD: ['Annapolis', 'Baltimore', 'Bethesda', 'Frederick', 'Gaithersburg'],
  MA: ['Boston', 'Cambridge', 'Lowell', 'Springfield', 'Worcester'],
  MI: ['Ann Arbor', 'Detroit', 'Flint', 'Grand Rapids', 'Kalamazoo', 'Lansing'],
  MN: ['Duluth', 'Minneapolis', 'Rochester', 'St. Paul'],
  MS: ['Biloxi', 'Gulfport', 'Jackson', 'Tupelo'],
  MO: ['Columbia', 'Kansas City', 'Springfield', 'St. Louis'],
  MT: ['Billings', 'Bozeman', 'Great Falls', 'Missoula'],
  NE: ['Lincoln', 'Omaha'],
  NV: ['Henderson', 'Las Vegas', 'Reno', 'Sparks'],
  NH: ['Concord', 'Manchester', 'Nashua'],
  NJ: ['Newark', 'Jersey City', 'Paterson', 'Trenton'],
  NM: ['Albuquerque', 'Las Cruces', 'Santa Fe'],
  NY: ['Albany', 'Buffalo', 'New York City', 'Rochester', 'Syracuse', 'Yonkers'],
  NC: ['Asheville', 'Charlotte', 'Durham', 'Greensboro', 'Raleigh', 'Winston-Salem'],
  ND: ['Bismarck', 'Fargo', 'Grand Forks'],
  OH: ['Akron', 'Cincinnati', 'Cleveland', 'Columbus', 'Dayton', 'Toledo'],
  OK: ['Norman', 'Oklahoma City', 'Tulsa'],
  OR: ['Bend', 'Eugene', 'Portland', 'Salem'],
  PA: ['Allentown', 'Erie', 'Philadelphia', 'Pittsburgh', 'Scranton'],
  RI: ['Providence', 'Warwick'],
  SC: ['Charleston', 'Columbia', 'Greenville', 'Spartanburg'],
  SD: ['Rapid City', 'Sioux Falls'],
  TN: ['Chattanooga', 'Knoxville', 'Memphis', 'Nashville'],
  TX: ['Austin', 'Dallas', 'El Paso', 'Fort Worth', 'Houston', 'Lubbock', 'San Antonio', 'Waco'],
  UT: ['Logan', 'Ogden', 'Provo', 'Salt Lake City', 'St. George'],
  VT: ['Burlington', 'Montpelier'],
  VA: ['Arlington', 'Charlottesville', 'Norfolk', 'Richmond', 'Roanoke', 'Virginia Beach'],
  WA: ['Bellevue', 'Seattle', 'Spokane', 'Tacoma', 'Vancouver'],
  WV: ['Charleston', 'Huntington', 'Morgantown'],
  WI: ['Green Bay', 'Madison', 'Milwaukee', 'Racine'],
  WY: ['Casper', 'Cheyenne', 'Jackson'],
}
